// next/app/about/page.tsx
export default function Page() {
  return (
    <>
      <div className="flex h-full flex-1 flex-col justify-center gap-4 p-2 text-center">
        <p>PTools is created by Patrick Miller</p>
        <p>
          <a
            href="https://github.com/patdx"
            className="text-eggplant underline"
          >
            github.com/patdx
          </a>
        </p>
      </div>
    </>
  );
}

// src/pages/about.vue
<script lang="tsx">
export default {
  setup() {
    return () => (
      <div class="flex h-full flex-1 flex-col justify-center gap-4 p-2 text-center">
        <p>PTools is created by Patrick Miller</p>
        <p>
          <a href="https://github.com/patdx" class="text-eggplant underline">
            github.com/patdx
          </a>
        </p>
      </div>
    );
  },
};
</script>
