// next/app/clock/clock.tsx
'use client';

import { useIsSSR } from '@react-aria/ssr';
import clsx from 'clsx';
import { Checkbox, Label } from 'flowbite-react';
import { DateTime } from 'luxon';
import {
  makeAutoObservable,
  reaction,
  runInAction
} from 'mobx';
import { observer } from 'mobx-react-lite';
import { now } from 'mobx-utils';
import { useEffect } from 'react';

const state = makeAutoObservable(
  {
    showConfig: false,
    toggleConfig() {
      this.showConfig = !this.showConfig;
    },

    showSeconds: true,
    toggleShowSeconds() {
      this.showSeconds = !this.showSeconds;
    },

    show24: true,
    toggleShow24() {
      this.show24 = !this.show24;
    },

    get timeInSeconds() {
      const epoch = now(1000);

      const formatter = this.show24
        ? this.showSeconds
          ? DateTime.TIME_24_WITH_SECONDS
          : DateTime.TIME_24_SIMPLE
        : this.showSeconds
        ? DateTime.TIME_WITH_SECONDS
        : DateTime.TIME_SIMPLE;

      return DateTime.fromMillis(epoch).toLocaleString(formatter);

      // .set({ millisecond: 0 }).toISOTime({
      //   includeOffset: false,
      //   suppressMilliseconds: true,
      //   suppressSeconds: !this.showSeconds,
      // });
    },
  },
  {},
  {
    autoBind: true,
  },
);

export const Clock = observer(function Clock() {
  const isSSR = useIsSSR();

  useEffect(() => {
    wakeLockTracker.lock();
    return () => {
      wakeLockTracker.release();
    };
  }, []);

  return (
    <>
      {state.showConfig ? (
        <Config />
      ) : (
        <div className="absolute inset-0 flex items-center justify-center dark:bg-black">
          <div
            className={clsx(
              'tabular-nums dark:text-eggplant-700',
              state.timeInSeconds.length > 8 ? 'text-[15vw]' : 'text-[20vw]',
            )}
          >
            {isSSR ? '00:00:00' : state.timeInSeconds}
          </div>
        </div>
      )}
      <button
        className={clsx(
          'absolute right-0 top-0 p-2 text-eggplant hover:underline active:underline dark:text-eggplant-700',
          state.showConfig && 'font-bold',
        )}
        onClick={state.toggleConfig}
      >
        Settings
      </button>
    </>
  );
});

const Config = observer(function Config() {
  return (
    <div className="p-2 text-xl">
      <div className="flex items-center gap-1">
        <Checkbox
          id="seconds-checkbox"
          checked={state.showSeconds}
          onChange={state.toggleShowSeconds}
        />
        <Label htmlFor="seconds-checkbox" className="flex-1">
          Show seconds
        </Label>
      </div>

      <div className="flex items-center gap-1">
        <Checkbox
          size={20}
          id="time24-checkbox"
          checked={state.show24}
          onChange={state.toggleShow24}
        />
        <Label htmlFor="time24-checkbox" className="flex-1">
          Use 24 time
        </Label>
      </div>
    </div>
  );
});

const wakeLockTracker = makeAutoObservable({
  targetStatus: 'released' as 'released' | 'locked',
  status: 'released' as 'released' | 'locking' | 'locked' | 'releasing',
  wakeLockPromise: null as Promise<WakeLockSentinel> | null,
  wakeLock: null as WakeLockSentinel | null,

  get isLocked() {
    return this.wakeLock != null;
  },
  async lock(): Promise<void> {
    this.targetStatus = 'locked';
  },
  async release(): Promise<void> {
    this.targetStatus = 'released';
  },
});

// src/pages/clock.vue
<script setup lang="ts">
import clsx from 'clsx';
import { Observer } from 'mobx-vue-lite';
import { useWakeLock } from '../utils/wake-lock-tracker';

useWakeLock();
</script>

<template>
  <Observer>
    <ClockConfig v-if="clockState.showConfig" />
    <div
      v-else
      className="absolute inset-0 flex items-center justify-center dark:bg-black"
    >
      <div
        :class="
          clsx(
            'tabular-nums dark:text-eggplant-700',
            clockState.timeInSeconds.length > 8 ? 'text-[15vw]' : 'text-[20vw]'
          )
        "
      >
        <!-- {isSSR ? '00:00:00' : state.timeInSeconds} -->
        {{ clockState.timeInSeconds }}
      </div>
    </div>
    <button
      :class="
        clsx(
          'absolute right-0 top-0 p-2 text-eggplant hover:underline active:underline dark:text-eggplant-700',
          clockState.showConfig && 'font-bold'
        )
      "
      @click="clockState.toggleConfig"
    >
      Settings
    </button>
  </Observer>
</template>
